excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Quaydar.github.io
title: Awesome
email: q@quaydar.com
author: Quaydar
description: My awesome new site
paginate: 5
google_analytics: 