excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://www.quaydar.com
title: Quaystats
email: q@quaydar.com
author: Quaydar
description: Stats for college football
paginate: 5
google_analytics: 
