excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://www.quaydar.com
title: Quaydar
email: q@quaydar.com
author: Quaydar
description: Quaydar's cfb stats
paginate: 5
google_analytics: 
